### ISSUE TITLE
v3 - TODO

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/graphql-controllers#46]
- [x] Integration tests
- [x] Use of @Factory annotation to create Input types
- [x] Refactoring: remove RegistryInterface (Registry is just another Container interface that does autowiring + a bunch of getters on services
- [ ] create a GraphQL interface if we put a @Type annotation on an actual interface.

**Comment by moufmouf** [comment]
- [ ] Fix issue: the @Type annotation does not seem to work with **relative** class name (only absolute starting with a \)
